irssi: lots of updates, see README.md

diff --git a/irssi/Dockerfile b/irssi/Dockerfile
--- a/irssi/Dockerfile
+++ b/irssi/Dockerfile
@@ -4,6 +4,7 @@ MAINTAINER dreamcat4 <dreamcat4@gmail.com>
 
 ENV _clean="rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*"
 ENV _apt_clean="eval apt-get clean && $_clean"
+# apt-get clean -y && apt-get autoclean -y && apt-get autoremove -y
 
 
 # Install s6-overlay
@@ -20,22 +21,129 @@ RUN tar -zxf /tmp/pipework-master.tar.gz -C /tmp && cp /tmp/pipework-master/pipe
 
 
 # Install bitlbee, znc, irssi, tmux, sshd and other supportive pkgs
-RUN apt-get update && apt-get install -y wget git sudo znc \
- libtime-duration-perl bitlbee bitlbee-plugin-otr \
- libwww-perl libnotify-bin libmime-base64-urlsafe-perl \
- irssi irssi-scripts irssi-plugin-otr irssi-plugin-xmpp \
- tmux openssh-server socat nano less nmap man && $_apt_clean
+RUN apt-get update -qqy && DEBIAN_FRONTEND=noninteractive apt-get install -y wget apt-transport-https ca-certificates \
+ && wget -O- https://code.bitlbee.org/debian/release.key | apt-key add - \
+ && echo "deb http://code.bitlbee.org/debian/master/wily/amd64/ ./" >> /etc/apt/sources.list \
+ && wget -O- https://jgeboski.github.io/obs.key | apt-key add - \
+ && echo "deb http://download.opensuse.org/repositories/home:/jgeboski/xUbuntu_15.10 ./" >> /etc/apt/sources.list \
+ && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C03AA79CFFEBD240 \
+ && echo "deb http://ppa.launchpad.net/aap/pidgin/ubuntu wily main" >> /etc/apt/sources.list \
+ && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 531EE72F4C9D234C \
+ && echo "deb http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu wily main" >> /etc/apt/sources.list \
+ && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D1820DB22A11534E \
+ && echo "deb https://weechat.org/ubuntu wily main" >> /etc/apt/sources.list \
+ \
+ && apt-get update -qqy && DEBIAN_FRONTEND=noninteractive apt-get install -y \
+    git sudo znc ngircd \
+    libtime-duration-perl rsyslog bitlbee-libpurple bitlbee-plugin-otr \
+    bitlbee-steam bitlbee-facebook \
+    pidgin-sipe pidgin-skypeweb telegram-purple \
+    python-dev python-pip pkg-config graphviz graphviz-dev python-cobe \
+    libwww-perl libnotify-bin libmime-base64-urlsafe-perl \
+    irssi make cpanminus irssi-scripts irssi-plugin-otr irssi-plugin-xmpp \
+    weechat weechat-plugins \
+    tmux openssh-server socat nano less man nmap \
+ \
+ && cpanm WebService::HipChat Algorithm::Diff \
+ && pip install --upgrade pip \
+ && pip install -r https://raw.githubusercontent.com/ProgVal/Limnoria/master/requirements.txt --upgrade \
+ && pip install limnoria --upgrade && chmod +x /usr/local/bin/supybot* \
+ && pip install -r https://raw.githubusercontent.com/ProgVal/Supybot-plugins/master/requirements.txt --upgrade \
+ && wget -q -O- https://raw.githubusercontent.com/GLolol/SupyPlugins/master/requirements.txt | grep -v "Limnoria.git" > /tmp/glol.reqs.txt \
+ && pip install -r /tmp/glol.reqs.txt --upgrade && rm /tmp/glol.reqs.txt \
+ \
+ && $_apt_clean
+
+# For irssi / adv_windowlist.pl:
+ # && cpanm Text::CharWidth \
 
 
-# Download scripts from https://scripts.irssi.org, and the irssi theme 'weed'
+
+# Hack, install older version of libprotobuf to meed dependancies
+# This whatsapp-purple PPA needs newer ubuntu version as trusty 14.04 too old now
+RUN wget -O /tmp/libprotobuf8_amd64.deb http://security.ubuntu.com/ubuntu/pool/main/p/protobuf/libprotobuf8_2.5.0-9ubuntu1_amd64.deb && dpkg -i /tmp/libprotobuf8_amd64.deb \
+ && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C777F0E392FAE28B \
+ && echo "deb http://ppa.launchpad.net/whatsapp-purple/ppa/ubuntu trusty main" >> /etc/apt/sources.list \
+ && apt-get update -qqy && DEBIAN_FRONTEND=noninteractive apt-get install -y pidgin-whatsapp \
+ && $_apt_clean
+
+
+# NOTE: overlayfs bug causes pip dependancies install failure below ^^;
+#   https://github.com/docker/docker/issues/12327#issuecomment-171496303
+#   https://gist.github.com/amercader/4432ed33a73d510b4a08
+#
+# Using patch / feature branch with Frog's rejected PIP pr ! didnt work
+# RUN apt-get update && apt-get install -y python-dev python-pip && pip install --upgrade pip \
+#  && pip install git+https://github.com/FragLegs/pip@patch-for-issue-2953 && $_apt_clean
+
+
+
+# Spline plugins with broken deps: "Stock Tweety WebHooks WorldTime"
+# ENV _spline_plugins="GitPull LogTail Series Stock Supybot-Pastebin Travis Tweety UrbanDictionary Weather WebHooks WolframAlpha WorldTime ZNC"
+ENV _spline_plugins="GitPull LogTail Series Supybot-Pastebin Travis UrbanDictionary Weather WebHooks WolframAlpha ZNC"
+
+RUN mkdir -p limnoria-plugins/spline \
+ && for _spline_plugin in $_spline_plugins; \
+ do wget -q -O- https://raw.githubusercontent.com/reticulatingspline/${_spline_plugin}/master/requirements.txt | grep -v "Limnoria.git" > /tmp/spline.reqs.txt || break ; \
+    echo "processing deps for \"reticulatingspline/${_spline_plugin}\":" && cat /tmp/spline.reqs.txt && echo \
+ && pip install -r /tmp/spline.reqs.txt --upgrade && rm /tmp/spline.reqs.txt && echo \
+  ; done \
+ \
+ && for _spline_plugin in $_spline_plugins; \
+ do git clone https://github.com/reticulatingspline/${_spline_plugin} limnoria-plugins/spline/${_spline_plugin} \
+  ; done \
+ && $_apt_clean
+
+
+
+# ! TEMP for bitlbee torchat, znc-push module
+RUN apt-get update -qqy && DEBIAN_FRONTEND=noninteractive apt-get install -y tor libcurl3 && $_apt_clean
+
+
+# Bitlbee - libpurpletorchat
+ENV _torchat_ver="2.0-alpha-14"
+RUN wget -O /tmp/libpurpletorchat.tbz https://github.com/downloads/prof7bit/TorChat/libpurpletorchat-${_torchat_ver}-linux-x86-64.tar.bz2 \
+ && tar -C /usr/lib/purple-2 --strip-components=1 -jxvf /tmp/libpurpletorchat.tbz libpurpletorchat/libpurpletorchat.so && $_apt_clean
+
+
+# TODO: Future (not ready yet) - tox-prpl - https://github.com/jin-eld/tox-prpl/issues/54
+
+
+# Irssi - Download scripts and themes
 RUN git clone https://github.com/irssi/scripts.irssi.org.git \
- && git clone https://github.com/ronilaukkarinen/weed.git
+ && git clone https://github.com/irssi-import/themes.git \
+ && git clone https://github.com/huyz/irssi-colors-solarized
+
+RUN mkdir -p limnoria-plugins \
+ && git clone https://github.com/ProgVal/Supybot-plugins limnoria-plugins/progval \
+ && git clone https://github.com/GLolol/SupyPlugins limnoria-plugins/glolol
+
+
+RUN echo Checking limnoria was installed && ls -lsa /usr/local/bin/supybot
 
 
 # Setup bitlbee user
-RUN groupmod -o -g 6667 bitlbee \
- && usermod -o -u 6667 -g bitlbee --shell /bin/bash -d /config/bitlbee bitlbee \
+RUN groupmod -o -g 6111 bitlbee \
+ && usermod -o -u 6111 -g bitlbee --shell /bin/bash -d /config/bitlbee bitlbee \
  && install -o bitlbee -g bitlbee -d /config/bitlbee
+
+
+# Setup xtheme user
+RUN groupadd -o -g 8153 xtheme \
+ && useradd -o -u 8153 -g xtheme --shell /bin/bash -d /config/xtheme xtheme \
+ && install -o xtheme -g xtheme -d /config/xtheme
+
+
+# Setup ngircd user
+RUN groupadd -o -g 5914 ngircd \
+ && useradd -o -u 5914 -g ngircd --shell /bin/bash -d /config/ngircd ngircd \
+ && install -o ngircd -g ngircd -d /config/ngircd
+
+
+# Setup limnoria user
+RUN groupadd -o -g 1135 limnoria \
+ && useradd -o -u 1135 -g limnoria --shell /bin/bash -d /config/limnoria limnoria \
+ && install -o limnoria -g limnoria -d /config/limnoria
 
 
 # Setup znc user
@@ -51,8 +159,12 @@ RUN groupadd -o -g 22 irssi \
  && install -o irssi -g irssi -d /config/irssi
 
 
+# Sudo without password
+RUN echo "irssi ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
+
+
 # Setup sshd
-ENV tmux_socket="/tmp/tmux.irssi.sock" tmux_session="tmux"
+ENV TERM="tmux-256color" tmux_socket="/tmp/tmux.irssi.sock" tmux_session="tmux" tmux_irc_clients="irssi weechat"
 RUN mkdir -p /var/run/sshd \
  && echo "\n\n\
 # Container specific sshd settings\n\
@@ -73,8 +185,17 @@ ENV S6_LOGGING="0"
 ADD services.d /etc/services.d
 
 
+# ! temp
+COPY znc-modules-linux-x86_64.tar.gz /tmp/
+RUN tar zxf /tmp/znc-modules-linux-x86_64.tar.gz -C /usr/lib/znc/ --skip-old-files && $_clean
+
+COPY xtheme-linux-x86_64.tar.gz /tmp/
+RUN tar zxf /tmp/xtheme-linux-x86_64.tar.gz -C / --skip-old-files && $_clean
+
+
 # Default container settings
-VOLUME /config /logs
+RUN echo Regenerating apt cache && apt-get update -qqy
+VOLUME /config /irc
 EXPOSE 6697 22
 ENTRYPOINT ["/init"]
 
